Repository Cool-Potatoes/flight-booking, pull requests merged in 2025-01, with the labels that each got.

#12 Feature/payment/crud
  payment-service/src/main/java/com/flight_booking/payment_service/PaymentServiceApplication.java
  payment-service/src/main/java/com/flight_booking/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/flight_booking/payment_service/domain/model/BaseEntity.java
  payment-service/src/main/java/com/flight_booking/payment_service/domain/model/Payment.java
  payment-service/src/main/java/com/flight_booking/payment_service/domain/model/PaymentStatusEnum.java
  payment-service/src/main/java/com/flight_booking/payment_service/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/configuration/JpaConfig.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/repository/PaymentRepositoryCustom.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/repository/PaymentRepositoryCustomImpl.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/global/ApiResponse.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/global/exception/GlobalExceptionHandler.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/request/PaymentRequestDto.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/response/PaymentResponseDto.java
Labels: enhancement

#10 예매 생성 및 커스텀 Response 클래스 적용
  booking-service/.gitattributes
  booking-service/.gitignore
  booking-service/build.gradle
  booking-service/gradle/wrapper/gradle-wrapper.jar
  booking-service/gradle/wrapper/gradle-wrapper.properties
  booking-service/gradlew
  booking-service/gradlew.bat
  booking-service/settings.gradle
  booking-service/src/main/java/com/flight_booking/booking_service/BookingServiceApplication.java
  booking-service/src/main/java/com/flight_booking/booking_service/application/dto/BookingDto.java
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/BookingService.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/config/JpaConfig.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/BaseEntity.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/Booking.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/BookingStatusEnum.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/repository/BookingRepository.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/client/Passenger.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/client/PassengerTypeEnum.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/client/SeatClassEnum.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/repository/BookingRepositoryCustom.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/repository/BookingRepositoryImpl.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/controller/BookingController.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/ApiResponse.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/BusinessException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/ErrorCode.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/GlobalExceptionHandler.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/booking/NotFountBookingException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/booking/NotFountBookingIdException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/request/BookingRequestDto.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/response/BookingResponseCustomDto.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/response/BookingResponseDto.java
  booking-service/src/main/resources/application.yml
  booking-service/src/test/java/com/flight_booking/booking_service/BookingServiceApplicationTests.java
  config-server/src/main/resources/config-repo/booking-service.yml
  config-server/src/main/resources/config-repo/gateway-service.yml
Labels: enhancement

#15 feat : flight-service 기초 파일 설정 & crud 임시 로직 구성
  config-server/src/main/resources/config-repo/flight-service.yml
  config-server/src/main/resources/config-repo/gateway-service.yml
  config-server/src/main/resources/config-repo/ticket-service.yml
  flight-service/.gitattributes
  flight-service/.gitignore
  flight-service/build.gradle
  flight-service/gradle/wrapper/gradle-wrapper.jar
  flight-service/gradle/wrapper/gradle-wrapper.properties
  flight-service/gradlew
  flight-service/gradlew.bat
  flight-service/settings.gradle
  flight-service/src/main/java/com/flight_booking/flight_service/FlightServiceApplication.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/FlightService.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/Airport.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/BaseEntity.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/Flight.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/FlightStatusEnum.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/Seat.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/SeatClassEnum.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/repository/AirportRepository.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/repository/FlightRepository.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/repository/SeatRepository.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/JpaConfig.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/repository/FlightRepositoryCustom.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/repository/FlightRepositoryCustomImpl.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/controller/ExternalFlightController.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/controller/InternalFlightController.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/global/ApiResponse.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/global/exception/GlobalExceptionHandler.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/request/FlightCreateRequestDto.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/request/FlightUpdateRequestDto.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/response/FlightDetailResponseDto.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/response/FlightListResponseDto.java
  flight-service/src/main/resources/application.yml
  flight-service/src/test/java/com/flight_booking/flight_service/FlightServiceApplicationTests.java
  ticket-service/.gitattributes
  ticket-service/.gitignore
  ticket-service/build.gradle
  ticket-service/gradle/wrapper/gradle-wrapper.jar
  ticket-service/gradle/wrapper/gradle-wrapper.properties
  ticket-service/gradlew
  ticket-service/gradlew.bat
  ticket-service/settings.gradle
  ticket-service/src/main/java/com/flight_booking/ticket_service/TicketServiceApplication.java
  ticket-service/src/main/resources/application.yml
  ticket-service/src/test/java/com/flight_booking/ticket_service/TicketServiceApplicationTests.java
Labels: enhancement

#17 Feat/payment/payment booking
  payment-service/build.gradle
  payment-service/src/main/java/com/flight_booking/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/flight_booking/payment_service/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/request/UpdateFareRequestDto.java
  payment-service/src/main/resources/application-test.yml
  payment-service/src/test/java/com/flight_booking/payment_service/payment/PaymentServiceTest.java
Labels: enhancement

#22 Feat/passenger/refactor
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/BookingService.java
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/PassengerService.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/Booking.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/BookingStatusEnum.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/Passenger.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/model/PassengerTypeEnum.java
  booking-service/src/main/java/com/flight_booking/booking_service/domain/repository/PassengerRepository.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/client/SeatClassEnum.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/repository/BookingRepositoryImpl.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/ErrorCode.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/booking/NotFoundBookingException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/booking/NotFoundBookingIdException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/passenger/InvalidPassengerListException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/global/exception/passenger/MissingRequiredFieldsException.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/request/BookingRequestDto.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/request/PassengerRequestDto.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/response/BookingResponseDto.java
  booking-service/src/main/java/com/flight_booking/booking_service/presentation/response/PassengerResponseDto.java
Labels: enhancement

#28 feat/gateway&user/Authentication
  config-server/src/main/resources/config-repo/gateway-service.yml
  config-server/src/main/resources/config-repo/user-service.yml
  gateway-service/build.gradle
  gateway-service/src/main/java/com/flight_booking/gateway_service/filter/CustomPostFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/filter/CustomPreFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/filter/JwtAuthenticationFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/util/JwtErrorCode.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/util/JwtUtil.java
  user-service/build.gradle
  user-service/src/main/java/com/flight_booking/user_service/UserServiceApplication.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/BaseEntity.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/Role.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/User.java
  user-service/src/main/java/com/flight_booking/user_service/domain/repository/UserRepository.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/persistence/AuditorAwareImpl.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/persistence/JpaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/SecurityConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/authentication/AuthenticationFilter.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/authentication/CustomUserDetails.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/authentication/CustomUserDetailsService.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/jwt/JwtUtil.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/jwt/PasswordEncoderConfig.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/AuthController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/UserController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/ApiResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/UserException.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/SignInRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/SignUpRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/UserResponse.java
Labels: enhancement

#36 Feat: User CRUD
  user-service/build.gradle
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/BaseEntity.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/User.java
  user-service/src/main/java/com/flight_booking/user_service/domain/repository/UserRepository.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/QueryDslConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/persistence/AuditorAwareImpl.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/persistence/JpaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/repository/UserRepositoryCustom.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/repository/UserRepositoryImpl.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/authentication/CustomUserDetails.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/AuthController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/UserController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/ApiResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/UpdateRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/AdminUserDetailResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/PageResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/UserDetailResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/UserListResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/UserResponse.java
Labels: enhancement

#44 Fix: flightRequestDto 이름 미 변경 오류 해결,
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/BookingService.java
  common/src/main/java/com/flight_booking/common/application/dto/SeatBookingRequestDto.java
  config-server/src/main/resources/config-repo/flight-service.yml
  config-server/src/main/resources/config-repo/ticket-service.yml
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/SeatService.java
  flight-service/src/main/java/com/flight_booking/flight_service/domain/model/Seat.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/ConsumerApplicationKafkaConfig.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/ProducerApplicationKafkaConfig.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/controller/FlightController.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/controller/SeatController.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/global/ApiResponse.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/global/exception/GlobalExceptionHandler.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/controller/PaymentController.java
Labels: bug

#42 Feat: 로그인 시 블락/탈퇴 회원 처리
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/BlockService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/BlockedInfo.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/User.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/BlockController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/UserController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/UserException.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/BlockRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/AdminUserDetailResponse.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/UserResponse.java
Labels: enhancement

#49 Feat: 아이디, 비밀번호 관련 기능 구현
  common/src/main/java/com/flight_booking/common/application/dto/NotificationRequestDto.java
  config-server/src/main/resources/config-repo/notification-service.yml
  gateway-service/src/main/java/com/flight_booking/gateway_service/filter/JwtAuthenticationFilter.java
  notification-service/build.gradle
  notification-service/src/main/java/com/flight_booking/notification_service/NotificationServiceApplication.java
  notification-service/src/main/java/com/flight_booking/notification_service/application/service/NotificationService.java
  notification-service/src/main/java/com/flight_booking/notification_service/global/configuration/ConsumerApplicationKafkaConfig.java
  notification-service/src/main/java/com/flight_booking/notification_service/presentation/controller/NotificationController.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/PasswordService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/VerificationCodeService.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/User.java
  user-service/src/main/java/com/flight_booking/user_service/domain/repository/UserRepository.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/auditing/AuditorAwareImpl.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/ProducerApplicationKafkaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/RedisConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/SecurityConfig.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/AuthController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/PasswordController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/VerificationCodeController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/ChangePwRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/FindIdRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/ResetPwRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/SendCodeRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/VerificationCodeRequest.java
Labels: enhancement

#51 Update and rename 이슈-생성-템플릿.md to ISSUE-CREATION-TEMPLATE.md
  .github/ISSUE_TEMPLATE/ISSUE-CREATION-TEMPLATE.md
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
Labels: documentation

#52 fix: AuthService signin시 role 버그 수정
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
Labels: bug

#62 fix: ticket 이 1개만 생성되는 오류 수정
  ticket-service/src/main/java/com/flight_booking/ticket_service/application/service/TicketService.java
Labels: bug

#59 Feat/monitoring/prometeus
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/config/SecurityConfig.java
  config-server/src/main/resources/config-repo/booking-service.yml
  config-server/src/main/resources/config-repo/flight-service.yml
  config-server/src/main/resources/config-repo/gateway-service.yml
  config-server/src/main/resources/config-repo/notification-service.yml
  config-server/src/main/resources/config-repo/payment-service.yml
  config-server/src/main/resources/config-repo/ticket-service.yml
  config-server/src/main/resources/config-repo/user-service.yml
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/SecurityConfig.java
  notification-service/build.gradle
  notification-service/src/main/java/com/flight_booking/notification_service/infrastructure/config/SecurityConfig.java
  notification-service/src/main/resources/application.yml
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/configuration/SecurityConfig.java
  prometheus.yml
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/configuration/SecurityConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/SecurityConfig.java
Labels: enhancement

#63 Fix/kafka/set message
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/BookingService.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/messaging/BookingKafkaSender.java
  common/src/main/java/com/flight_booking/common/infrastructure/kafka/KafkaSender.java
  common/src/main/java/com/flight_booking/common/infrastructure/kafka/KafkaSenderImpl.java
  common/src/main/java/com/flight_booking/common/infrastructure/util/StackTraceUtils.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/FlightService.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/SeatService.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/messaging/kafkaSender/FlightKafkaSender.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/messaging/kafkaSender/SeatKafkaSender.java
  payment-service/src/main/java/com/flight_booking/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/messaging/PaymentKafkaSender.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/application/service/TicketService.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/messaging/TicketKafkaSender.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/messaging/UserKafkaSender.java
Labels: enhancement

#68 fix: Feign 호출시 인증 오류 해결
  common/src/main/java/com/flight_booking/common/infrastructure/security/AuthenticationFilter.java
  common/src/main/java/com/flight_booking/common/infrastructure/security/CustomUserDetails.java
Labels: bug

#66 fix: Common Main 클래스 삭제
  common/src/main/java/com/flight_booking/common/Main.java
Labels: enhancement

#78 fix: Kafka URL 설정 주입 처리
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/config/kafka/ConsumerApplicationKafkaConfig.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/config/kafka/ProducerApplicationKafkaConfig.java
  config-server/src/main/resources/config-repo/booking-service.yml
  config-server/src/main/resources/config-repo/flight-service.yml
  config-server/src/main/resources/config-repo/notification-service.yml
  config-server/src/main/resources/config-repo/payment-service.yml
  config-server/src/main/resources/config-repo/ticket-service.yml
  config-server/src/main/resources/config-repo/user-service.yml
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/kafka/ConsumerApplicationKafkaConfig.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/kafka/ProducerApplicationKafkaConfig.java
  notification-service/src/main/java/com/flight_booking/notification_service/global/configuration/ConsumerApplicationKafkaConfig.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/configuration/kafka/ConsumerApplicationKafkaConfig.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/configuration/kafka/ProducerApplicationKafkaConfig.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/configuration/kafka/ConsumerApplicationKafkaConfig.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/configuration/kafka/ProducerApplicationKafkaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/kafka/ConsumerApplicationKafkaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/kafka/ProducerApplicationKafkaConfig.java
Labels: enhancement

#73 Fix: 로그아웃 기능 수정 및 리프레시 토큰
  config-server/src/main/resources/config-repo/user-service.yml
  gateway-service/src/main/java/com/flight_booking/gateway_service/filter/JwtAuthenticationFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/util/JwtErrorCode.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/util/JwtUtil.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/util/RedisConfig.java
  notification-service/src/main/java/com/flight_booking/notification_service/NotificationServiceApplication.java
  notification-service/src/main/java/com/flight_booking/notification_service/application/service/NotificationService.java
  notification-service/src/main/java/com/flight_booking/notification_service/global/configuration/ConsumerApplicationKafkaConfig.java
  notification-service/src/main/java/com/flight_booking/notification_service/global/configuration/ProducerApplicationKafkaConfig.java
  notification-service/src/main/java/com/flight_booking/notification_service/infrastructure/messaging/NotificationKafkaEndpoint.java
  notification-service/src/main/java/com/flight_booking/notification_service/infrastructure/messaging/NotificationKafkaSender.java
  notification-service/src/main/java/com/flight_booking/notification_service/presentation/controller/NotificationController.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/VerificationCodeService.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/auditing/AuditorAwareImpl.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/SecurityConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/jwt/JwtUtil.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/AuthController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/PasswordController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/VerificationCodeController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
Labels: Optimizaion

#85 fix: Test 실패로 인한 깃액션 실패
  payment-service/src/main/resources/application-test.yml
  payment-service/src/test/java/com/flight_booking/payment_service/payment/PaymentServiceTest.java
Labels: bug

#76 Feat: PaymentRetryWorker 구현
  common/src/main/java/com/flight_booking/common/application/dto/PaymentRetryRequestDto.java
  config-server/src/main/resources/config-repo/payment-service.yml
  payment-service/src/main/java/com/flight_booking/payment_service/PaymentServiceApplication.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/messaging/PaymentRetryWorker.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/scheduling/PaymentScheduler.java
Labels: enhancement

#91 Feat: 결제 실패 재시도 구현 완료
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/BookingService.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/messaging/BookingKafkaEndpoint.java
  common/src/main/java/com/flight_booking/common/application/dto/PaymentRefundProcessRequestDto.java
  common/src/main/java/com/flight_booking/common/application/dto/PaymentRetryRequestDto.java
  common/src/main/java/com/flight_booking/common/application/dto/UserRequestDto.java
  common/src/main/java/com/flight_booking/common/domain/model/PaymentStatusEnum.java
  common/src/main/java/com/flight_booking/common/presentation/dto/NotificationRequest.java
  config-server/src/main/resources/config-repo/notification-service.yml
  notification-service/src/main/java/com/flight_booking/notification_service/application/service/NotificationService.java
  notification-service/src/main/java/com/flight_booking/notification_service/domain/model/Notification.java
  notification-service/src/main/java/com/flight_booking/notification_service/infrastructure/messaging/NotificationKafkaEndpoint.java
  notification-service/src/main/java/com/flight_booking/notification_service/presentation/controller/NotificationController.java
  payment-service/src/main/java/com/flight_booking/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/flight_booking/payment_service/application/service/user/UserService.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/client/UserClient.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/messaging/PaymentKafkaEndpoint.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/messaging/PaymentRetryWorker.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/scheduling/PaymentScheduler.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/service/UserServiceImpl.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/messaging/UserKafkaEndpoint.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/UserController.java
Labels: enhancement

#88 Feat: 사용자 블락/탈퇴한 회원 gateway에서 검증
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/UserStatusDto.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/UserStatusService.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/JwtUtil.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/config/RedisConfig.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/config/WebClientConfig.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/filter/CustomPostFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/filter/JwtAuthenticationFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/GatewayController.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/exception/ErrorResponseUtil.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/exception/JwtErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/application/dto/UserStatusDto.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/SecurityConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/kafka/ProducerApplicationKafkaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/UserController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
Labels: enhancement

#101 feat: Ticket update 기능 @RetryableTopic, Circuitbreaker 적용
  booking-service/src/main/java/com/flight_booking/booking_service/application/service/BookingService.java
  booking-service/src/main/java/com/flight_booking/booking_service/infrastructure/messaging/BookingKafkaEndpoint.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/FlightService.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/SeatService.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/messaging/DltService.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/messaging/SeatDltHandler.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/messaging/kafkaEndpoint/FlightKafkaEndpoint.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/messaging/kafkaEndpoint/SeatKafkaEndpoint.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/service/UserServiceImpl.java
  payment-service/src/main/java/com/flight_booking/payment_service/application/service/PaymentService.java
  payment-service/src/main/java/com/flight_booking/payment_service/infrastructure/messaging/PaymentKafkaEndpoint.java
  payment-service/src/main/java/com/flight_booking/payment_service/presentation/controller/PaymentController.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/application/service/BookingService.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/application/service/FlightService.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/application/service/TicketService.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/application/service/UserService.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/configuration/RedisConfig.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/feign/BookingClient.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/feign/FlightClient.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/feign/UserClient.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/messaging/TicketKafkaEndpoint.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/service/BookingServiceImpl.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/service/FlightServiceImpl.java
  ticket-service/src/main/java/com/flight_booking/ticket_service/infrastructure/service/UserServiceImpl.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/messaging/UserKafkaEndpoint.java
Labels: Optimizaion

#103 Feat: Gemini API를 이용한 질문 응답 기능 제공
  config-server/src/main/resources/config-repo/flight-service.yml
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/AiService.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/AnswerService.java
  flight-service/src/main/java/com/flight_booking/flight_service/infrastructure/configuration/RestClientConfig.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/controller/AiController.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/request/RegulationQuestionDto.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/request/WeatherQuestionDto.java
Labels: enhancement

#109 docs: readme 작성
  README.md
Labels: documentation

#110 docs: readme 완성본
  README.md
Labels: documentation

#105 Refactor: 인증/인가 관련 리팩토링
  config-server/src/main/resources/config-repo/gateway-service.yml
  config-server/src/main/resources/config-repo/user-service.yml
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/AiService.java
  flight-service/src/main/java/com/flight_booking/flight_service/application/service/AnswerService.java
  flight-service/src/main/java/com/flight_booking/flight_service/presentation/controller/AiController.java
  gateway-service/build.gradle
  gateway-service/src/main/java/com/flight_booking/gateway_service/GatewayServiceApplication.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/UserStatusService.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/dto/UserInfoDto.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/dto/UserStatusDto.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/service/CacheService.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/application/service/UserInfoService.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/JwtAuthenticationFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/JwtUtil.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/config/FeignConfig.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/config/RedisConfig.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/config/WebClientConfig.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/feign/FeignClientConfig.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/feign/UserFallback.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/feign/UserFeignClient.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/filter/CustomPostFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/infrastructure/filter/CustomPreFilter.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/GatewayController.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/exception/CustomJwtException.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/exception/ErrorResponseUtil.java
  gateway-service/src/main/java/com/flight_booking/gateway_service/presentation/exception/JwtErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/AuthService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/BlockService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/PasswordService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/application/service/VerificationCodeService.java
  user-service/src/main/java/com/flight_booking/user_service/domain/model/User.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/RedisConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/SecurityConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/kafka/ConsumerApplicationKafkaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/configuration/kafka/ProducerApplicationKafkaConfig.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/repository/UserRepositoryImpl.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/AuthenticationFilter.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/CustomUserDetails.java
  user-service/src/main/java/com/flight_booking/user_service/infrastructure/security/jwt/JwtUtil.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/AuthController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/controller/UserController.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/ErrorCode.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/global/exception/UserException.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/request/DeleteRequest.java
  user-service/src/main/java/com/flight_booking/user_service/presentation/response/PageResponse.java
Labels: Optimizaion

#106 Feat: User 마일리지 조회 Pessimistic lock 적용
  payment-service/src/test/java/com/flight_booking/payment_service/payment/PaymentServiceTest.java
  user-service/build.gradle
  user-service/src/main/java/com/flight_booking/user_service/application/service/UserService.java
  user-service/src/main/java/com/flight_booking/user_service/domain/repository/UserRepository.java
  user-service/src/main/resources/application-test.yml
  user-service/src/test/java/com/flight_booking/user_service/user/UserServiceConcurrencyTest.java
Labels: Optimizaion
